question_data = [{"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                  "question": "Liechtenstein does not have an airport.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "General Knowledge",
                                                  "question": "Haggis is traditionally ate on Burns Night.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                                  "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium", "category": "Politics",
                                                  "question": "Helen Clark was the 37th Prime Minister of Australia.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Cartoon &amp; Animations",
                                                  "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby&#039;s All-Star Laff-a-Lympics.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                  "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Film",
                                                  "question": "There aren&#039;t any live-action clones in &quot;Star Wars: Episode III - Revenge of the Sith&quot;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Science: Computers",
                                                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                  "question": "Seoul is the capital of North Korea.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]}]
